/*
Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package generator_gui;

import timemanager.TimeManager_Container;
import timemanager.TimeManager_DayPair;

/**
 *Window for adding data
 * @author kubaw
 */
public class addrecord_window extends javax.swing.JDialog {

    
    TimeManager_Container session_tmc;
    /**
     * Creates new form addrecord_window
     */
    public addrecord_window(java.awt.Frame parent, boolean modal,TimeManager_Container session_tmc) {
        super(parent, modal);
        this.session_tmc = session_tmc; 
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field_data = new javax.swing.JTextField();
        button_add = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add data record");

        field_data.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        button_add.setText("Add");
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("DD.MM.YYYY[HH:MM-HH:MM]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field_data)
                    .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_data, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Function for data verification
     * @return Boolean 
     */
    boolean verify_data(){
        String data = field_data.getText();
        
        if ( data.contains("[") && data.contains("]") ){
            
            if ( data.contains("-")){
                
                return true;
            }
        }
        return false;
    }
    
    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed
        if ( verify_data() ){
            String data = field_data.getText();
            
            TimeManager_DayPair tmdp = new TimeManager_DayPair(data);
            
            if( tmdp.validation_flag ){
                session_tmc.time_objects.add(tmdp);
                dispose();
            }
            else{
                dispose();
            }
        }
    }//GEN-LAST:event_button_addActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JTextField field_data;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
