/*
Jakub Wawak
kubawawak@gmail.com
all rights reserved
 */
package generator_gui;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JComboBox;
import timemanager.TimeManager_Object;

/**
 *Object for creating generator window
 * @author jakubwawak
 */
public class generator_window extends javax.swing.JFrame {

    /**
     * Creates new form generator_window
     */
    ArrayList<JComboBox> group_from,group_to;
    
    /**
     * Constructor
     */
    public generator_window() {
        initComponents();
        
        group_from = new ArrayList<>();
        group_to = new ArrayList<>();
        
        group_from.add(combobox_dayfrom);
        group_from.add(combobox_monthfrom);
        group_from.add(combobox_yearfrom);
        
        group_to.add(combobox_dayto);
        group_to.add(combobox_monthto);
        group_to.add(combobox_yearto);
        
        this.setLocationRelativeTo(null);
        load_window();
        setVisible(true);
    }
    
    /**
     * Function for loading window
     */
    void load_window(){
        System.out.println("Loading window");
        LocalDateTime actual_time = LocalDateTime.now( ZoneId.of( "Europe/Warsaw" ) );
        System.out.println("Setting time for: "+actual_time.toString());
        TimeManager_Object tmo = new TimeManager_Object(actual_time);
        Generator_DatePreparer gdp_to = new Generator_DatePreparer(actual_time);
        Generator_DatePreparer gdp_from = new Generator_DatePreparer(tmo.day_difference(30));
        textarea_raw.setText("Brak danych do wyświetlenia...");
        gdp_to.load_comboboxdata(group_to);
        gdp_from.load_comboboxdata(group_from);
    }

    /**
     * Function for updating groups of comboboxes
     * @param group 
     */
    void update_group(ArrayList<JComboBox> group){
        System.out.println("Updating group...");
        // get data
        int day = Integer.parseInt(group.get(0).getSelectedItem().toString());
        String month = group.get(1).getSelectedItem().toString();
        int year = Integer.parseInt(group.get(2).getSelectedItem().toString());
        System.out.println("Raw input: "+day+" "+month+" "+year);
        Generator_DatePreparer gdp = new Generator_DatePreparer(day,month,year);
        gdp.show_data();
        gdp.load_comboboxdata(group);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combobox_dayfrom = new javax.swing.JComboBox<>();
        combobox_monthfrom = new javax.swing.JComboBox<>();
        combobox_yearfrom = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combobox_dayto = new javax.swing.JComboBox<>();
        combobox_monthto = new javax.swing.JComboBox<>();
        combobox_yearto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        button_generate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea_raw = new javax.swing.JTextArea();
        button_export = new javax.swing.JButton();
        button_close = new javax.swing.JButton();
        button_sendasemail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        button_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generator raportów osobistych");

        combobox_dayfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combobox_monthfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combobox_monthfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox_monthfromActionPerformed(evt);
            }
        });

        combobox_yearfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("od:");

        combobox_dayto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combobox_monthto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        combobox_yearto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("do:");

        button_generate.setText("GENERUJ");

        textarea_raw.setColumns(20);
        textarea_raw.setRows(5);
        jScrollPane1.setViewportView(textarea_raw);

        button_export.setText("Eksportuj do pliku");

        button_close.setText("Zamknij");
        button_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_closeActionPerformed(evt);
            }
        });

        button_sendasemail.setText("Wyślij w wiadomości e-mail");

        jLabel3.setText("Generujesz raport dla konta:");

        button_reset.setText("Reset okna");
        button_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(combobox_dayfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_monthfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_yearfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(combobox_dayto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_monthto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combobox_yearto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(button_generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(button_close, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button_sendasemail, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_export, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button_reset)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(button_reset))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_generate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox_dayfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_monthfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_yearfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combobox_dayto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_monthto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox_yearto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_export)
                    .addComponent(button_close)
                    .addComponent(button_sendasemail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_closeActionPerformed
        dispose();
    }//GEN-LAST:event_button_closeActionPerformed

    private void button_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resetActionPerformed
        load_window();
    }//GEN-LAST:event_button_resetActionPerformed

    private void combobox_monthfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox_monthfromActionPerformed
        update_group(group_from);
    }//GEN-LAST:event_combobox_monthfromActionPerformed
    //--------------------------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_close;
    private javax.swing.JButton button_export;
    private javax.swing.JButton button_generate;
    private javax.swing.JButton button_reset;
    private javax.swing.JButton button_sendasemail;
    private javax.swing.JComboBox<String> combobox_dayfrom;
    private javax.swing.JComboBox<String> combobox_dayto;
    private javax.swing.JComboBox<String> combobox_monthfrom;
    private javax.swing.JComboBox<String> combobox_monthto;
    private javax.swing.JComboBox<String> combobox_yearfrom;
    private javax.swing.JComboBox<String> combobox_yearto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea_raw;
    // End of variables declaration//GEN-END:variables
}
